# yaml-language-server: $schema=./version.yml

jobs:
  - job: "Version_App"
    displayName: "Version App"
    steps:
      - checkout: self
        fetchDepth: 0

      - task: gitversion/setup@0
        displayName: Install GitVersion
        inputs:
          versionSpec: '5.x'

      - task: gitversion/execute@0
        displayName: Determine version
        inputs:
          useConfigFile: true
          configFilePath: gitVersion.yml

      - script: |
          echo ##vso[task.setvariable variable=Version;isOutput=true]$(GitVersion.SemVer)
        name: SetVersion